apiVersion: batch/v1
kind: CronJob
metadata:
  name: oidc-token-fetcher
  namespace: moreillon
spec:
  schedule: "*/15 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: oidc-token-fetcher
          restartPolicy: Never
          containers:
            - name: kubectl
              # TODO: use a simpler image
              image: moreillon/ci-dind:v1.0.4
              command:
                - /bin/bash
                - /script.sh
              volumeMounts:
                - mountPath: /script.sh
                  name: oidc-token-fetcher
                  subPath: script.sh
              envFrom:
                - secretRef:
                    name: oidc-m2m-token-fetcher-env
          volumes:
            - name: oidc-token-fetcher
              configMap:
                name: oidc-token-fetcher
